version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - sam package --s3-bucket $BUCKET --output-template-file backend-template.yml
artifacts:
  files:
    - backend-template.yml