Transform: AWS::Serverless-2016-10-31

Resources:
  GraphQLResolverCreateTodo:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      FieldName: "createTodo"
      TypeName: "Mutation"
      DataSourceName: !GetAtt TodoDataSource.Name
      ResponseMappingTemplateS3Location: ./graphql/createTodo/responseMapping.vtl
      RequestMappingTemplateS3Location: ./graphql/createTodo/requestMapping.vtl
  GraphQLResolverListTodo:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      FieldName: "listTodos"
      TypeName: "Query"
      DataSourceName: !GetAtt TodoDataSource.Name
      ResponseMappingTemplateS3Location: ./graphql/listTodos/responseMapping.vtl
      RequestMappingTemplateS3Location: ./graphql/listTodos/requestMapping.vtl
  GraphQLResolverGetTodo:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      FieldName: "getTodo"
      TypeName: "Query"
      DataSourceName: !GetAtt TodoDataSource.Name
      ResponseMappingTemplateS3Location: ./graphql/getTodo/responseMapping.vtl
      RequestMappingTemplateS3Location: ./graphql/getTodo/requestMapping.vtl
  GraphQLResolverUpdateTodo:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      FieldName: "updateTodo"
      TypeName: "Mutation"
      DataSourceName: !GetAtt TodoDataSource.Name
      ResponseMappingTemplateS3Location: ./graphql/updateTodo/responseMapping.vtl
      RequestMappingTemplateS3Location: ./graphql/updateTodo/requestMapping.vtl
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      DefinitionS3Location: ./graphql/schema.graphql
  TodoDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
      ServiceRoleArn: !GetAtt TodoDataSourceServiceRole.Arn
      Type: RELATIONAL_DATABASE
      RelationalDatabaseConfig:
        RdsHttpEndpointConfig:
          AwsRegion: !Ref AWS::Region
          DbClusterIdentifier: arn:aws:rds:eu-west-1:031521953183:cluster:db-todos
          AwsSecretStoreArn: arn:aws:secretsmanager:eu-west-1:031521953183:secret:todo-rds-secret-HpAxoN
          DatabaseName: todosdb
        RelationalDatabaseSourceType: RDS_HTTP_ENDPOINT
      Name: TodoDataSource
  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLEndpoint.ApiId
  GraphQLEndpoint:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: TodoApi
  TodoDataSourceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: RdsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - rds-data:ExecuteSql
                  - rds-data:ExecuteStatement
                  - rds-data:GetItems
                  - rds-data:InsertItems
                  - rds-data:UpdateItems
                Resource:
                  - "arn:aws:rds:eu-west-1:031521953183:cluster:db-todos"
                  - "arn:aws:rds:eu-west-1:031521953183:cluster:db-todos:*"
              -
                Effect: "Allow"
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - "arn:aws:secretsmanager:eu-west-1:031521953183:secret:todo-rds-secret-HpAxoN"
Outputs:
  GraphQLUrl:
    Value: !GetAtt GraphQLEndpoint.GraphQLUrl
  ApiKey:
    Value: !GetAtt GraphQLApiKey.ApiKey
  Region:
    Value: !Ref AWS::Region
  AuthType:
    Value: API_KEY
  Version:
    Value: 6
