// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://7mygrsaxwjbsrlkwz26ykb5nya.appsync-api.eu-west-1.amazonaws.com/graphql ",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yxcc5viypjc4tdbkrzp57xgd4i",
};

export default awsmobile;